[package]
name = "redirector"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
mysql_async = "0.36.1"
redis = "0.32.4"
tokio = { version = "1.46.1", features = ["full"] }
urlencoding = "2.1"
