services:
  redirector:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
    # MariaDB
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=mydb
    restart: always